export const FETCH_LIST_RESTART = 'FETCH_LIST_RESTART'
export const FETCH_LIST_START = 'FETCH_LIST_START'
export const FETCH_LIST_SUCCESS = 'FETCH_LIST_SUCCESS'
export const FETCH_LIST_ERROR = 'FETCH_LIST_ERROR'

